// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD66PaysHmtonJePOQsCtcKfwZX3WVAb1g',
    appId: '1:916134396564:web:f46f538dcff2da06deaa81',
    messagingSenderId: '916134396564',
    projectId: 'projects-17ef7',
    authDomain: 'projects-17ef7.firebaseapp.com',
    storageBucket: 'projects-17ef7.firebasestorage.app',
    measurementId: 'G-6FD78241TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX80dUcs7AWaSFujPp8MzgFglHbE7mZ-Q',
    appId: '1:916134396564:android:111cf3f98a244ce4deaa81',
    messagingSenderId: '916134396564',
    projectId: 'projects-17ef7',
    storageBucket: 'projects-17ef7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNef-V1ai1VWbfeq8HEyTDVZtC60g8erA',
    appId: '1:916134396564:ios:efb986f4b7a0414ddeaa81',
    messagingSenderId: '916134396564',
    projectId: 'projects-17ef7',
    storageBucket: 'projects-17ef7.firebasestorage.app',
    iosBundleId: 'com.example.devtrack',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNef-V1ai1VWbfeq8HEyTDVZtC60g8erA',
    appId: '1:916134396564:ios:efb986f4b7a0414ddeaa81',
    messagingSenderId: '916134396564',
    projectId: 'projects-17ef7',
    storageBucket: 'projects-17ef7.firebasestorage.app',
    iosBundleId: 'com.example.devtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD66PaysHmtonJePOQsCtcKfwZX3WVAb1g',
    appId: '1:916134396564:web:2d17eec7dd9d23c1deaa81',
    messagingSenderId: '916134396564',
    projectId: 'projects-17ef7',
    authDomain: 'projects-17ef7.firebaseapp.com',
    storageBucket: 'projects-17ef7.firebasestorage.app',
    measurementId: 'G-L9Z5PKK6KV',
  );
}
