// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPVBCXNeNCehWX9GJpdXm18Y25mCf-Us',
    appId: '1:432574294952:web:2d73647e5f2c7deb8bcb9d',
    messagingSenderId: '432574294952',
    projectId: 'devtrack-de0ff',
    authDomain: 'devtrack-de0ff.firebaseapp.com',
    storageBucket: 'devtrack-de0ff.firebasestorage.app',
    measurementId: 'G-JG717HD3ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgLD5KD8oF8q-eMa_IGGBXgecpIz1ykFY',
    appId: '1:432574294952:android:64c249f65dbd49e28bcb9d',
    messagingSenderId: '432574294952',
    projectId: 'devtrack-de0ff',
    storageBucket: 'devtrack-de0ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0P-UMyZIkCa-EyxyFwsjwFH8JxNzW4U',
    appId: '1:432574294952:ios:df088096eeac4d258bcb9d',
    messagingSenderId: '432574294952',
    projectId: 'devtrack-de0ff',
    storageBucket: 'devtrack-de0ff.firebasestorage.app',
    iosBundleId: 'com.example.devtrack',
  );
}
